spring:
  jpa:
    repositories:
      enabled: true
    dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  datasource:
    url: jdbc:postgresql://${HOST}:${PORT}/${DB_NAME}
    username: ${USERNAME}
    password: ${PASSWORD}
    name: ${NAME}
    driver-class-name: org.postgresql.Driver
#
#  sql:
#    init:
#      mode: always