spring:
  jpa:
    defer-datasource-initialization: true
    repositories:
      enabled: true
    dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  datasource:
    url: jdbc:mysql://185.107.113.9:3306/p575286_emails
    username: p575286_Camiel
    password: Poedersuiker9?
#  sql:
#    init:
#      mode: always

